### ISSUE TITLE
[Request] .sav Dumping

### ISSUE THREAD

**Issue by GB-CG** [FIX94/gba-link-cable-dumper#1]
Any possibility?

Thanks for making this cool app, works great for me so far.

**Comment by FIX94** [comment]
good to hear it works great for you, I only had 3 gba games laying around to test it and since all 3 came out with the correct hash I just went ahead and released it. I probably will add save support at a later point.

**Comment by FIX94** [comment]
just pushed out a new release, it works with my 3 gba games I had laying around (all EEPROM saves)

**Comment by GB-CG** [comment]
Ooh nice. I'll check it out in a bit.

**Comment by GB-CG** [comment]
Um, it's giving me a cpgz file when I open the zip file. EDIT: Never mind, I got the file.

**Comment by FIX94** [comment]
well I had the wrong settings selected when compressing so I also re-uploaded it with my regular ones ;)

**Comment by SuperrSonic** [comment]
Many thanks for this, I always wanted to backup my saves.

I dumped and tested on mGBA:
Four games with 64KB Flash.
Two games with SRAM.
And one game with 8KB EEPROM.

**Comment by FIX94** [comment]
that sounds incredible! I had to do quite a fair amount of work for my EEPROM saves to get read out properly so if the others just work right off thats great!

**Comment by GB-CG** [comment]
Yeah, I backed up the saves of Mario Kart Super Circuit, Pokémon Ruby, Metroid Fusion onto mGBA and it works perfectly.

However, I also tried restoring a save onto Metorid Fusion (PAL, AMTP01) and it got an error saying 'Save has the wrong size'. What am I doing wrong?

**Comment by FIX94** [comment]
I assume it detected it wrong at that time, I know sometimes the EEPROM detection can be wrong

**Comment by FIX94** [comment]
just looked at fusion and its only a SRAM save so it should be 32KB no matter what, can you confirm that? because then I would not understand why it failed to restore right now.

**Comment by GB-CG** [comment]
The restore worked with Mario Kart Super Circuit (512k flash) and Superstar Saga (EEPROM 4k/64k)

I opened my Metroid Fusion cart and it's 256k SRAM. I could try again. Yes, It is 32kb.

**Comment by GB-CG** [comment]
Ok, now it works! I think what happened before is that I dumped Fusion on v1.0 and then I backed up the save on v1.1 and it didn't work. Version conflict?

So what I've done is, delete the rom from 1.0, then redump the rom _and_  the save on v1.1 and it worked!

**Comment by FIX94** [comment]
thats entirely possible. also I just pushed up v1.2 with now for sure fixed eeprom support, tested it with 3 eeprom games over and over again and didnt have any detection issues anymore.

**Comment by GB-CG** [comment]
I tried v1.2 and that didn't work either.

~~Try using my save to see if it works on your end. This save is from the 1.0 metroid dump.~~
_(Link removed since the issue's been resolved)_

**Comment by FIX94** [comment]
...wait, why is that one 64kb instead of 32?

**Comment by GB-CG** [comment]
I don't know. When I dumped my metroid save with v1.1, that's what I got.

**Comment by FIX94** [comment]
well you only get a 64kb save with FLASH but there is no FLASH string in metroid fusion as far as I can tell...

**Comment by FIX94** [comment]
so really I couldnt tell you how that happend to be honest, maybe some FAT error?

**Comment by GB-CG** [comment]
I mean, it's working fine now when I redumped the save. As you say, sometimes the EEPROM detection can be wrong. Here's the inside of the cart:
![img_0177](https://cloud.githubusercontent.com/assets/11931125/14405030/d07d771e-fe7c-11e5-8063-2855b98a80a8.JPG)

**Comment by FIX94** [comment]
lets hope there wont be other issues I guess ;)

**Comment by GB-CG** [comment]
I'm going to try backup my collection and see how that goes.

For now, I think it's safe to close this issue. Despite the odd issues, thanks again for adding this cool feature. :)
Update 22/12/2016: No problems so far! Thanks again.
