### ISSUE TITLE
GBA SP support ?

### ISSUE THREAD

**Issue by u1735067** [FIX94/gba-link-cable-dumper#10]
Hi, is it supposed to work with GBA SP ?
Because I can't get past "Waiting for a GBA on port 2...". I tried v1.6, then 1.2 and 1.3 (with almost no hope it would be different).
The controller in port 1 is recognized (exit is working).

**Comment by FIX94** [comment]
I exclusively tested it with a gba sp, you sure your link cable is properly plugged in and you booted it without any game inserted? also some cables simply seem to not work properly for some reason so it may just be your cable having issues.

**Comment by u1735067** [comment]
Yep, even tried to start it before or after the homebrew is launched, and at first I tried with the Select+Start technique.
The cable is (as far as I can remember) an official (and I used it in the past on Wind Waker).
There's another Wii I'll be able to try it on so I'll do that (and write a feedback if I don't forget), otherwise I may use https://www.insidegadgets.com/projects/gbxcart-rw/.
As the main question is answered, I close, thank you :)

**Comment by u1735067** [comment]
For reference, it is this one https://commons.wikimedia.org/wiki/File:Gamecube_-_GBA_cable_adapter_-_Third_Party.JPG, and it seems not to be an official one (plus no marking on it) :(
![Link cable](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Gamecube_-_GBA_cable_adapter_-_Third_Party.JPG/347px-Gamecube_-_GBA_cable_adapter_-_Third_Party.JPG)
