### ISSUE TITLE
Prototype GBA cart boots on cart insertion, won't dump

### ISSUE THREAD

**Issue by ajshell1** [FIX94/gba-link-cable-dumper#19]
So, I have a prototype GBA cart that I recently purchased for a significant amount of money. It seems to work fine on my GBA SP (although there are a few signs that it it isn't a finished build, notably in the form of some bugs).

I want to dump it and preserve it. But there's just one problem:

Whenever I stick the cart in, the game itself starts (showing the nintendo logo).

So I get to the point where the homebrew is loaded onto the GBA, and I insert the cart, only for the homebrew to exit and the game to start, as if I was turning the system on with the cart in the system.

This has never happened for any of the retail carts I've owned, and I've dumped several with this software without issue.

Strangely, if I turn the system on without a cart in it, the normal GBA boot screen shows up, but when I insert that cart at this point, it starts as normal. I don't think this happens for normal GBA carts.

A friend of mine suggested that this may be due to the ROM header having a debug flag set.

Anyway, the end result is that I can't dump the game with my Wii + GBA SP setup.

I'm begging you, PLEASE help me solve this. I want to preserve the contents of this cart.

**Comment by FIX94** [comment]
hey there, have you tried starting your GBA with the cart inserted while holding down start+select? I think that should skip booting the game and may allow you to start the dumper from there.

**Comment by ajshell1** [comment]
IT WORKS! THANK YOU SO MUCH!

Or at least, the dumping process has started. I'll close this issue once I'm sure that this program doesn't have any difficulties getting matching dumps from this cart.

My big concern is that the cart has a sticker on it that says "64M", while this program says that the ROM size is 16.00MB. The original game is 8.00MB, which is equal to 64 MegaBITS, which is what I thought the 64M stood for. 

Note to myself for future refernce:

Power on the GBA with the cart inserted, while holding start and select

Then start the homebrew on the Wii and plug in the GBA.

**Comment by FIX94** [comment]
Who knows, perhaps it did not detect the size properly and its making an overdump now which would not be the end of the world to cut off.

**Comment by ajshell1** [comment]
So, it dumped sucessfully, and I think it is an overdump.

I used 
`dd if=orig.gba of=firsthalf.gba count=8192 bs=1024`
and
`dd if=orig.gba of=secondhalf.gba skip=8192 count=8192 bs=1024`

to split the output, and both halves were identical.

I dumped it a second time and got the same checksum.

**Comment by FIX94** [comment]
awesome! I suppose I can close this issue now and perhaps try and reword the readme a bit to be a bit more clear about the start+select thing so people understand it better.
