### ISSUE TITLE
Frogger's Adventures: Temple of the Frog fails to dump

### ISSUE THREAD

**Issue by Moriyama3** [FIX94/gba-link-cable-dumper#3]
> Game Name: FROG: TEMPLE
> Game ID: AFRE
> Company ID: A4
> ROM Size: 4.00MB
> Save Size: 0.50 KB
> 
> ERROR: Could not create file! Exit...

I'm guessing that it's trying to create "FROG: TEMPLE [AFREA4].sav" or "FROG: TEMPLE [AFREA4].gba" and fails because colons aren't allowed in filenames?  All of my other gba games worked perfectly.

**Comment by FIX94** [comment]
yea thats probably what breaks it, now it should work just fine though.

**Comment by Moriyama3** [comment]
Yep, was just able to dump the game and its save successfully.  Thanks.
