### ISSUE TITLE
After launching the DOL the Screen turns black

### ISSUE THREAD

**Issue by unknowntrojan** [FIX94/gba-link-cable-dumper#5]
As said, after launching the newest version 1.6, the Screen turns black and only 2 slight white dots come visible.
DOL-001, AGB-001, DOL-011 (With Cartridge and tested without too!)

**Comment by FIX94** [comment]
if you look at the code its very simple so not a whole lot can go wrong, if you never see anything on screen then it probably hangs trying to mount the sd gecko, maybe meaning its sd card does not initialize.

**Comment by unknowntrojan** [comment]
The SD Card is working fine. the dumps folder has been created

**Comment by FIX94** [comment]
it it a problem with the screen not displaying anything then? because after that it should just loop the wait message...

**Comment by unknowntrojan** [comment]
should i upload a cam video?
used both newer and old versions btw.
but every homebrew is working fine! gcos, swiss, tetris

**Comment by FIX94** [comment]
well did you try to actually turn on the GBA connected to slot 2 to see if it even connects after it started? that would give us a indication if its even running.

**Comment by unknowntrojan** [comment]
he is always connected to port 4

**Comment by unknowntrojan** [comment]
,working

**Comment by FIX94** [comment]
wait, so it was just in the wrong port the whole time? guess you did not read the readme of the project...

**Comment by unknowntrojan** [comment]
yeah, sorry for the inconvience.
