### ISSUE TITLE
freeze bug

### ISSUE THREAD

**Issue by EzioisAwesome56** [FIX94/gba-link-cable-dumper#8]
so after I dump a rom, the program freezes and it wont let me dump a another game. please fix this or atleast let it respond to me pressing reset

**Comment by FIX94** [comment]
never had any freezes here and I have no clue why it ever would other than the link cable being dodgy and not properly sending all signals through...

**Comment by EzioisAwesome56** [comment]
Well, im not using official cables, but they worked for four swords, so I dunno

not to mention trying to launch ch the dumps in vba gave me "unknown arm op code: arm 00"

could it be the cables?

**Comment by FIX94** [comment]
most likely yes, that means on top of that freezing the games also arent dumped correctly.

**Comment by EzioisAwesome56** [comment]
well, that sucks, those are my only cables
ah well, at least they correctly send data to the gba

thanks for the info
